## MMTHE01 - Masters Thesis

### D. Thesis - Compute Kendall Coefficient of feature importance rankings

#### Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import os
import time
from scipy.stats import kendalltau

In [2]:
# Check your current working directory
cwd = os.getcwd()

# Define your relative path
relative_path = r"Analysis/intermediate_output/XAI all features ranked"  # adjust this relative to cwd

# Build the full path
full_path = os.path.join(cwd, relative_path)

# Check if it exists before changing
if os.path.exists(full_path):
    os.chdir(full_path)
    print("Changed directory to:", full_path)
else:
    print("Folder does not exist:", full_path)

Changed directory to: C:\Users\eaber\Documents\Masters Thesis Final\Analysis/intermediate_output/XAI all features ranked

#### Load Dataset

##### Import Local XAI feature importances

In [3]:
XGBoost_shap_local_allR = pd.read_csv('XGBoost_shap_local_allR.csv')
XGBoost_lime_allR = pd.read_csv('XGBoost_lime_allR.csv')
XGBoost_counterfactual_allR = pd.read_csv('XGBoost_counterfactual_allR.csv')

In [4]:
SVM_shap_local_allR = pd.read_csv('SVM_shap_local_allR.csv')
SVM_lime_allR = pd.read_csv('SVM_lime_allR.csv')
SVM_counterfactual_allR = pd.read_csv('SVM_counterfactual_allR.csv')

In [5]:
ANN_shap_local_allR = pd.read_csv('ANN_shap_local_allR.csv')
ANN_lime_allR = pd.read_csv('ANN_lime_allR.csv')
ANN_counterfactual_allR = pd.read_csv('ANN_counterfactual_allR.csv')
ANN_Local_Integrated_Gradient_allR = pd.read_csv('ANN_Local_Integrated_Gradient_allR.csv')

##### Import Global XAI feature importances

In [6]:
XGBoost_shap_global_allR = pd.read_csv('XGBoost_shap_global_allR.csv')
XGBoost_splime_allR = pd.read_csv('XGBoost_splime_allR.csv')
XGBoost_permutation_importance_allR = pd.read_csv('XGBoost_permutation_importance_allR.csv')

In [7]:
SVM_shap_global_allR = pd.read_csv('SVM_shap_global_allR.csv')
SVM_splime_allR = pd.read_csv('SVM_splime_allR.csv')
SVM_permutation_importance_allR = pd.read_csv('SVM_permutation_importance_allR.csv')

In [8]:
ANN_shap_global_allR = pd.read_csv('ANN_shap_global_allR.csv')
ANN_splime_allR = pd.read_csv('ANN_splime_allR.csv')
ANN_permutation_importance_allR = pd.read_csv('ANN_permutation_importance_allR.csv')
ANN_Global_Integrated_Gradient_allR = pd.read_csv('ANN_Global_Integrated_Gradient_allR.csv')

#### 1 Obtain Importance Dataframes - XGBoost

##### 1.1 Obtain Importance Dataframes - XGBoost Local Methods

In [9]:
XGBoost_shap_local_importance = XGBoost_shap_local_allR[['feature','abs_shap_value']].copy()

In [10]:
XGBoost_shap_local_importance.rename(columns={'abs_shap_value':'shap_local'},inplace=True)

In [11]:
XGBoost_local_importance1=XGBoost_shap_local_importance.merge(XGBoost_lime_allR[['feature','abs_contribution']],
                                                              on='feature',how='left')

In [12]:
XGBoost_local_importance1.rename(columns={'abs_contribution':'lime'},inplace=True)

In [13]:
XGBoost_Local_Methods_Importances=XGBoost_local_importance1.merge(XGBoost_counterfactual_allR[['feature','abs_delta']],
                                                              on='feature',how='left')

In [14]:
XGBoost_Local_Methods_Importances.rename(columns={'abs_delta':'counterfactual'},inplace=True)

##### 1.2 Obtain Importance Dataframes - XGBoost Global Methods

In [15]:
XGBoost_shap_global_importance = XGBoost_shap_global_allR[['feature','abs_shap_value_mean']].copy()

In [16]:
XGBoost_shap_global_importance.rename(columns={'abs_shap_value_mean':'shap_global'},inplace=True)

In [17]:
XGBoost_global_importance1=XGBoost_shap_global_importance.merge(XGBoost_splime_allR[['feature','abs_average_contribution']],
                                                              on='feature',how='left')

In [18]:
XGBoost_global_importance1.rename(columns={'abs_average_contribution':'splime'},inplace=True)

In [19]:
XGBoost_Global_Methods_Importances=XGBoost_global_importance1.merge(XGBoost_permutation_importance_allR[['feature','abs_importance_mean']],
                                                              on='feature',how='left')

In [20]:
XGBoost_Global_Methods_Importances.rename(columns={'abs_importance_mean':'permutation_importance'},inplace=True)

##### 1.3 Obtain Importance Dataframes - XGBoost All Methods

In [21]:
XGBoost_XAI_Methods_Importances = XGBoost_Local_Methods_Importances.merge(XGBoost_Global_Methods_Importances,on='feature',how='left')

In [22]:
XGBoost_XAI_Methods_Importances.head(1)

,feature,shap_local,lime,counterfactual,shap_global,splime,permutation_importance
0,title,1.35869,0.002264,0.094546,1.129659,0.030905,0.013565

In [23]:
#XGBoost_XAI_Methods_Importances_No_Counterfactual = XGBoost_local_importance1.merge(XGBoost_Global_Methods_Importances,on='feature',how='left')

In [24]:
#XGBoost_XAI_Methods_Importances_No_Counterfactual

#### 2 Obtain Importance Dataframes - SVM

##### 2.1 Obtain Importance Dataframes - SVM Local Methods

In [25]:
SVM_shap_local_importance = SVM_shap_local_allR[['feature','abs_shap_value']].copy()

In [26]:
SVM_shap_local_importance.rename(columns={'abs_shap_value':'shap_local'},inplace=True)

In [27]:
SVM_local_importance1=SVM_shap_local_importance.merge(SVM_lime_allR[['feature','abs_contribution']],
                                                              on='feature',how='left')

In [28]:
SVM_local_importance1.rename(columns={'abs_contribution':'lime'},inplace=True)

In [29]:
SVM_Local_Methods_Importances=SVM_local_importance1.merge(SVM_counterfactual_allR[['feature','abs_delta']],
                                                              on='feature',how='left')

In [30]:
SVM_Local_Methods_Importances.rename(columns={'abs_delta':'counterfactual'},inplace=True)

##### 2.2 Obtain Importance Dataframes - SVM Global Methods

In [31]:
SVM_shap_global_importance = SVM_shap_global_allR[['feature','abs_shap_value_mean']].copy()

In [32]:
SVM_shap_global_importance.rename(columns={'abs_shap_value_mean':'shap_global'},inplace=True)

In [33]:
SVM_global_importance1=SVM_shap_global_importance.merge(SVM_splime_allR[['feature','abs_average_contribution']],
                                                              on='feature',how='left')

In [34]:
SVM_global_importance1.rename(columns={'abs_average_contribution':'splime'},inplace=True)

In [35]:
SVM_Global_Methods_Importances=SVM_global_importance1.merge(SVM_permutation_importance_allR[['feature','abs_importance_mean']],
                                                              on='feature',how='left')

In [36]:
SVM_Global_Methods_Importances.rename(columns={'abs_importance_mean':'permutation_importance'},inplace=True)

##### 2.3 Obtain Importance Dataframes - SVM All Methods

In [37]:
SVM_XAI_Methods_Importances = SVM_Local_Methods_Importances.merge(SVM_Global_Methods_Importances,on='feature',how='left')

In [38]:
SVM_XAI_Methods_Importances.head(1)

,feature,shap_local,lime,counterfactual,shap_global,splime,permutation_importance
0,sub_grade,0.249499,0.074671,1.24491,0.170437,0.066104,0.066058

#### 3 Obtain Importance Dataframes - ANN

##### 3.1 Obtain Importance Dataframes - ANN Local Methods

In [39]:
ANN_shap_local_importance = ANN_shap_local_allR[['feature','abs_shap_value']].copy()

In [40]:
ANN_shap_local_importance.rename(columns={'abs_shap_value':'shap_local'},inplace=True)

In [41]:
ANN_local_importance1=ANN_shap_local_importance.merge(ANN_lime_allR[['feature','abs_contribution']],
                                                              on='feature',how='left')

In [42]:
ANN_local_importance1.rename(columns={'abs_contribution':'lime'},inplace=True)

In [43]:
ANN_local_importance2=XGBoost_local_importance1.merge(ANN_counterfactual_allR[['feature','abs_delta']],
                                                              on='feature',how='left')

In [44]:
ANN_local_importance2.rename(columns={'abs_delta':'counterfactual'},inplace=True)

In [45]:
ANN_Local_Methods_Importances=ANN_local_importance2.merge(ANN_Local_Integrated_Gradient_allR[['feature','abs_attribution']],
                                                              on='feature',how='left')

In [46]:
ANN_Local_Methods_Importances.rename(columns={'abs_attribution':'Local Integrated Gradient'},inplace=True)

##### 3.2 Obtain Importance Dataframes - ANN Global Methods

In [47]:
ANN_shap_global_importance = ANN_shap_global_allR[['feature','abs_shap_value_mean']].copy()

In [48]:
ANN_shap_global_importance.rename(columns={'abs_shap_value_mean':'shap_global'},inplace=True)

In [49]:
ANN_global_importance1=ANN_shap_global_importance.merge(ANN_splime_allR[['feature','abs_average_contribution']],
                                                              on='feature',how='left')

In [50]:
ANN_global_importance1.rename(columns={'abs_average_contribution':'splime'},inplace=True)

In [51]:
ANN_global_importance2=ANN_global_importance1.merge(ANN_permutation_importance_allR[['feature','abs_importance_mean']],
                                                              on='feature',how='left')

In [52]:
ANN_global_importance2.rename(columns={'abs_importance_mean':'permutation_importance'},inplace=True)

In [53]:
ANN_Global_Methods_Importances=ANN_global_importance2.merge(ANN_Global_Integrated_Gradient_allR[['feature','abs_importance']],
                                                              on='feature',how='left')

In [54]:
ANN_Global_Methods_Importances.rename(columns={'abs_importance':'Global Integrated Gradient'},inplace=True)

##### 3.3 Obtain Importance Dataframes - ANN All Methods

In [55]:
ANN_XAI_Methods_Importances = ANN_Local_Methods_Importances.merge(ANN_Global_Methods_Importances,on='feature',how='left')

In [56]:
ANN_XAI_Methods_Importances.head(1)

,feature,shap_local,lime,counterfactual,Local Integrated Gradient,shap_global,splime,permutation_importance,Global Integrated Gradient
0,title,1.35869,0.002264,1.330851,0.028056,0.012715,0.004436,0.002135,0.005553

##### Function to create Kendall Matrix and Score

In [57]:
def kendalls_w(feature_importances_df):
    """
    Compute Kendall’s W (Coefficient of Concordance).

    Parameters
    ----------
    ranks_df : pd.DataFrame
        Rows are items (e.g., features),
        columns are judges/methods,
        values are ranks (1 = highest importance).

    Returns
    -------
    float
        Kendall's W in [0, 1]
    """
    feature_importances_values = feature_importances_df.drop(columns=['feature'])
    
    # Convert importances to ranks (highest importance -> rank 1)
    ranks_df = feature_importances_values.rank(ascending=False)
    
    # Number of items (n) and judges (m)
    n, m = ranks_df.shape

    # Sum of ranks for each item
    R = ranks_df.sum(axis=1)

    # Mean of rank sums
    R_bar = R.mean()

    # Sum of squared deviations
    S = ((R - R_bar) ** 2).sum()

    # Kendall's W formula
    W = 12 * S / (m**2 * (n**3 - n))

    return W

#### 4 Calculate Kendall Coefficient for XAI Methods applied on XGBoost

##### 4.1 Calculate Kendall Coefficient for XAI Methods applied on XGBoost - Local XAI Methods

In [58]:
XGBoost_Local_Methods_kendall_W = kendalls_w(XGBoost_Local_Methods_Importances)

In [59]:
XGBoost_Local_Methods_kendall_W

0.28082327029695453

##### 4.2 Calculate Kendall Coefficient for XAI Methods applied on XGBoost - Global XAI Methods

In [60]:
XGBoost_Global_Methods_kendall_W = kendalls_w(XGBoost_Global_Methods_Importances)

In [61]:
XGBoost_Global_Methods_kendall_W

0.6612743981165033

##### 4.3 Calculate Kendall Coefficient for XAI Methods applied on XGBoost - All XAI Methods

In [62]:
XGBoost_XAI_Methods_kendall_W = kendalls_w(XGBoost_XAI_Methods_Importances)

In [63]:
XGBoost_XAI_Methods_kendall_W

0.37622085516822357

##### 4.4 Calculate Kendall Coefficient for XAI Methods applied on XGBoost - Local No Counterfactual

In [64]:
XGBoost_Local_Methods_Importances.head(1)

  feature  shap_local      lime  counterfactual
0   title     1.35869  0.002264        0.094546

In [65]:
XGBoost_Local_Methods_Importances_NoCounterfactual = XGBoost_Local_Methods_Importances.drop(columns={'counterfactual'})

In [66]:
XGBoost_Local_Methods_Importances_NoCounterfactual.head(1)

  feature  shap_local      lime
0   title     1.35869  0.002264

In [67]:
XGBoost_Local_Methods_NoCounterfactual_Kendall_W = kendalls_w(XGBoost_Local_Methods_Importances_NoCounterfactual)

In [68]:
XGBoost_Local_Methods_NoCounterfactual_Kendall_W

0.6248120300751879

##### 4.5 Calculate Kendall Coefficient for XAI Methods applied on XGBoost - Global No SP-LIME

In [69]:
XGBoost_Global_Methods_Importances.head(1)

  feature  shap_global    splime  permutation_importance
0   title     1.129659  0.030905                0.013565

In [70]:
XGBoost_Global_Methods_Importances_NoSPLime= XGBoost_Global_Methods_Importances.drop(columns={'splime'})

In [71]:
XGBoost_Global_Methods_Importances_NoSPLime.head(1)

  feature  shap_global  permutation_importance
0   title     1.129659                0.013565

In [72]:
XGBoost_Global_Methods_NoSPLime_Kendall_W = kendalls_w(XGBoost_Global_Methods_Importances_NoSPLime)

In [73]:
XGBoost_Global_Methods_NoSPLime_Kendall_W

0.9639097744360903

##### 4.6 Calculate Kendall Coefficient for XAI Methods applied on XGBoost - All XAI methods (No Counterfactual)

In [74]:
XGBoost_XAI_Methods_Importances_NoCounterfactual= XGBoost_XAI_Methods_Importances.drop(columns={'counterfactual'})

In [75]:
XGBoost_XAI_Methods_NoCounterfactual_Kendall_matrix_W = kendalls_w(XGBoost_XAI_Methods_Importances_NoCounterfactual)

In [76]:
XGBoost_XAI_Methods_NoCounterfactual_Kendall_matrix_W

0.5545919343814081

##### 4.7 Calculate Kendall Coefficient for XAI Methods applied on XGBoost - All XAI methods (No SPLIME)

In [77]:
XGBoost_XAI_Methods_Importances_SPLime= XGBoost_XAI_Methods_Importances.drop(columns={'splime'})

In [78]:
XGBoost_XAI_Methods_NoSPLime_Kendall_matrix_W = kendalls_w(XGBoost_XAI_Methods_Importances_SPLime)

In [79]:
XGBoost_XAI_Methods_NoSPLime_Kendall_matrix_W

0.41623513328776485

##### 4.8 Calculate Kendall Coefficient for XAI Methods applied on XGBoost - All XAI methods (No Counterfactual,No SPLIME)

In [80]:
XGBoost_XAI_Methods_Importances_NoCounterfactualSPLime= XGBoost_XAI_Methods_Importances.drop(columns={'counterfactual','splime'})

In [81]:
XGBoost_XAI_Methods_Importances_NoCounterfactualSPLime.head(1)

  feature  shap_local      lime  shap_global  permutation_importance
0   title     1.35869  0.002264     1.129659                0.013565

In [82]:
XGBoost_XAI_Methods_NoCounterfactualSPLime_Kendall_matrix_W = kendalls_w(XGBoost_XAI_Methods_Importances_NoCounterfactualSPLime)

In [83]:
XGBoost_XAI_Methods_NoCounterfactualSPLime_Kendall_matrix_W

0.6797676008202324

#### 5 Calculate Kendall Coefficient for XAI Methods applied on SVM

##### 5.1 Calculate Kendall Coefficient for XAI Methods applied on SVM - Local XAI Methods

In [84]:
SVM_Local_Methods_kendall_W = kendalls_w(SVM_Local_Methods_Importances)

In [85]:
SVM_Local_Methods_kendall_W

0.5325586694007747

##### 5.2 Calculate Kendall Coefficient for XAI Methods applied on SVM - Global XAI Methods

In [86]:
SVM_Global_Methods_kendall_W = kendalls_w(SVM_Global_Methods_Importances)

In [87]:
SVM_Global_Methods_kendall_W

0.7922989291410344

##### 5.3 Calculate Kendall Coefficient for XAI Methods applied on SVM - All XAI Methods

In [88]:
SVM_XAI_Methods_kendall_W = kendalls_w(SVM_XAI_Methods_Importances)

In [89]:
SVM_XAI_Methods_kendall_W

0.5900508847877269

##### 5.4 Calculate Kendall Coefficient for XAI Methods applied on SVM - Local No Counterfactual

In [90]:
SVM_Local_Methods_Importances_NoCounterfactual = SVM_Local_Methods_Importances.drop(columns={'counterfactual'})

In [91]:
SVM_Local_Methods_NoCounterfactual_Kendall_W = kendalls_w(SVM_Local_Methods_Importances_NoCounterfactual)

In [92]:
SVM_Local_Methods_NoCounterfactual_Kendall_W

0.7875939849624061

##### 5.5 Calculate Kendall Coefficient for XAI Methods applied on SVM - Global No SP-LIME

In [93]:
SVM_Global_Methods_Importances_NoSPLime= SVM_Global_Methods_Importances.drop(columns={'splime'})

In [94]:
SVM_Global_Methods_NoSPLime_Kendall_W = kendalls_w(SVM_Global_Methods_Importances_NoSPLime)

In [95]:
SVM_Global_Methods_NoSPLime_Kendall_W

0.9721462747778538

##### 5.6 Calculate Kendall Coefficient for XAI Methods applied on SVM - All XAI methods (No Counterfactual)

In [96]:
SVM_XAI_Methods_Importances_NoCounterfactal= SVM_XAI_Methods_Importances.drop(columns={'counterfactual'})

In [97]:
SVM_XAI_Methods_NoCounterfactual_Kendall_matrix_W = kendalls_w(SVM_XAI_Methods_Importances_NoCounterfactal)

In [98]:
SVM_XAI_Methods_NoCounterfactual_Kendall_matrix_W

0.7406807928913192

##### 5.7 Calculate Kendall Coefficient for XAI Methods applied on SVM - All XAI methods (No SPLIME)

In [99]:
SVM_XAI_Methods_Importances_NoSPLime= SVM_XAI_Methods_Importances.drop(columns={'splime'})

In [100]:
SVM_XAI_Methods_NoSPLime_Kendall_matrix_W = kendalls_w(SVM_XAI_Methods_Importances_NoSPLime)

In [101]:
SVM_XAI_Methods_NoSPLime_Kendall_matrix_W

0.6088092959671907

##### 5.8 Calculate Kendall Coefficient for XAI Methods applied on SVM - All XAI methods (No Counterfactual,No SPLIME)

In [102]:
SVM_XAI_Methods_Importances_NoCounterfactualSPLime= SVM_XAI_Methods_Importances.drop(columns={'counterfactual','splime'})

In [103]:
SVM_XAI_Methods_NoCounterfactualSPLime_Kendall_matrix_W = kendalls_w(SVM_XAI_Methods_Importances_NoCounterfactualSPLime)

In [104]:
SVM_XAI_Methods_NoCounterfactualSPLime_Kendall_matrix_W

0.7966592617908408

#### 6 Calculate Kendall Coefficient for XAI Methods applied on ANN

##### 6.1 Calculate Kendall Coefficient for XAI Methods applied on ANN - Local XAI Methods

In [105]:
ANN_Local_Methods_kendall_W = kendalls_w(ANN_Local_Methods_Importances)

In [106]:
ANN_Local_Methods_kendall_W

0.4242481203007519

##### 6.2 Calculate Kendall Coefficient for XAI Methods applied on ANN - Global XAI Methods

In [107]:
ANN_Global_Methods_kendall_W = kendalls_w(ANN_Global_Methods_Importances)

In [108]:
ANN_Global_Methods_kendall_W

0.6637645249487355

##### 6.3 Calculate Kendall Coefficient for XAI Methods applied on ANN - All XAI Methods

In [109]:
ANN_XAI_Methods_kendall_W = kendalls_w(ANN_XAI_Methods_Importances)

In [110]:
ANN_XAI_Methods_kendall_W

0.4605028195488722

##### 6.4 Calculate Kendall Coefficient for XAI Methods applied on ANN - Local No Counterfactual

In [111]:
ANN_Local_Methods_Importances_NoCounterfactual = ANN_Local_Methods_Importances.drop(columns={'counterfactual'})

In [112]:
ANN_Local_Methods_NoCounterfactual_Kendall_W = kendalls_w(ANN_Local_Methods_Importances_NoCounterfactual)

In [113]:
ANN_Local_Methods_NoCounterfactual_Kendall_W

0.5561479456216298

##### 6.5 Calculate Kendall Coefficient for XAI Methods applied on ANN - Global No SP-LIME

In [114]:
ANN_Global_Methods_Importances_NoSPLime= ANN_Global_Methods_Importances.drop(columns={'splime'})

In [115]:
ANN_Global_Methods_NoSPLime_Kendall_W = kendalls_w(ANN_Global_Methods_Importances_NoSPLime)

In [116]:
ANN_Global_Methods_NoSPLime_Kendall_W

0.795655806182122

##### 6.6 Calculate Kendall Coefficient for XAI Methods applied on ANN - All XAI methods (No Counterfactual)

In [117]:
ANN_XAI_Methods_Importances_NoCounterfactual = ANN_XAI_Methods_Importances.drop(columns={'counterfactual'})

In [118]:
ANN_XAI_Methods_NoCounterfactual_Kendall_matrix_W = kendalls_w(ANN_XAI_Methods_Importances_NoCounterfactual)

In [119]:
ANN_XAI_Methods_NoCounterfactual_Kendall_matrix_W

0.5317867953743357

##### 6.7 Calculate Kendall Coefficient for XAI Methods applied on ANN - All XAI methods (No SPLIME)

In [120]:
ANN_XAI_Methods_Importances_NoSPLime= ANN_XAI_Methods_Importances.drop(columns={'splime'})

In [121]:
ANN_XAI_Methods_NoSPLime_Kendall_matrix_W = kendalls_w(ANN_XAI_Methods_Importances_NoSPLime)

In [122]:
ANN_XAI_Methods_NoSPLime_Kendall_matrix_W

0.47251523986217864

##### 6.8 Calculate Kendall Coefficient for XAI Methods applied on ANN - All XAI methods (No Counterfactual,No SPLIME)

In [123]:
ANN_XAI_Methods_Importances_NoCounterfactualSPLime= ANN_XAI_Methods_Importances.drop(columns={'counterfactual','splime'})

In [124]:
ANN_XAI_Methods_NoCounterfactualSPLime_Kendall_matrix_W = kendalls_w(ANN_XAI_Methods_Importances_NoCounterfactualSPLime)

In [125]:
ANN_XAI_Methods_NoCounterfactualSPLime_Kendall_matrix_W

0.5691501480975165